version: "3.8"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autovermietungapp
    ports:
      - "3308:3306"

  app:
    build: .
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: autovermietungapp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "8080:8080"
