version: '3.8'
services:
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Tausend1308
      MYSQL_DATABASE: autovermietungapp
    ports:
      - "3306:3306"

  app:
    build: .
    depends_on:
      - mysqldb
    environment:
      DB_URL: jdbc:mysql://mysqldb:3306/autovermietungapp?createDatabaseIfNotExist=true
      DB_USERNAME: root
      DB_PASS: Tausend1308
    ports:
      - "8080:8080"
