
spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/autovermietungapp?useSSL=false&serverTimezone=UTC
    username: root
    password: Tausend1308
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
